default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= Rails.root.join("db/development.sqlite3") %>

test:
  <<: *default
  database: <%= Rails.root.join("db/test.sqlite3") %>

staging:
  <<: *default
  database: <%= Rails.root.join("db/staging.sqlite3") %>

production:
  <<: *default
  database: <%= Rails.root.join("db/production.sqlite3") %>
