#!/bin/bash
# Manual steps for deploying from staging to production

# Set variables
STAGING_APP_PATH="/opt/superapp-poc1"
PROD_SERVER="167.99.89.187"
TIMESTAMP=$(date +%Y-%m-%d-%H%M%S)

echo "===== MANUAL DEPLOYMENT STEPS ====="
echo ""
echo "Since SSH key authentication is not working, please follow these steps manually:"
echo ""
echo "1. ON PRODUCTION SERVER (${PROD_SERVER}), run these commands:"
echo "-----------------------------------------------------------"
echo "# Create backup directories"
echo "mkdir -p /opt/backups/databases-${TIMESTAMP}"
echo ""
echo "# Backup databases"
echo "cp -r /opt/superapp-poc1/db/*.sqlite3 /opt/backups/databases-${TIMESTAMP}/ 2>/dev/null || true"
echo "cp -r /opt/superapp-poc1/db/devices/*.sqlite3 /opt/backups/databases-${TIMESTAMP}/ 2>/dev/null || true"
echo ""
echo "# Create full backup"
echo "cd /opt && tar -czf /opt/backups/superapp-full-${TIMESTAMP}.tar.gz superapp-poc1"
echo ""
echo "# Stop Puma server"
echo "cd /opt/superapp-poc1 && pkill -f puma || true"
echo "-----------------------------------------------------------"
echo ""
echo "2. BACK ON STAGING SERVER, create a deployment package:"
echo "-----------------------------------------------------------"
echo "# Create a deployment package"
echo "cd /opt && tar -czf /tmp/deploy-package-${TIMESTAMP}.tar.gz \\"
echo "  --exclude='superapp-poc1/log/*.log' \\"
echo "  --exclude='superapp-poc1/tmp/pids/*' \\"
echo "  --exclude='superapp-poc1/tmp/sockets/*' \\"
echo "  --exclude='superapp-poc1/tmp/cache/*' \\"
echo "  --exclude='superapp-poc1/node_modules/*' \\"
echo "  superapp-poc1"
echo ""
echo "# Create a puma.rb config file for production"
echo "cat > /tmp/puma.rb << 'EOF'"
echo "# Puma configuration"
echo "threads_count = ENV.fetch(\"RAILS_MAX_THREADS\") { 5 }"
echo "threads threads_count, threads_count"
echo ""
echo "# Environment"
echo "environment ENV.fetch(\"RAILS_ENV\") { \"production\" }"
echo ""
echo "# Directory"
echo "directory ENV.fetch(\"RAILS_ROOT\") { Dir.pwd }"
echo ""
echo "# TCP binding"
echo "bind \"tcp://0.0.0.0:3000\""
echo ""
echo "# Logging"
echo "stdout_redirect \"log/puma.stdout.log\", \"log/puma.stderr.log\", true"
echo ""
echo "# Process management"
echo "pidfile ENV.fetch(\"PIDFILE\") { \"tmp/pids/server.pid\" }"
echo ""
echo "# Workers"
echo "workers ENV.fetch(\"WEB_CONCURRENCY\") { 2 }"
echo ""
echo "# Preload app for better performance"
echo "preload_app!"
echo ""
echo "# Plugin for clean restarts"
echo "plugin :tmp_restart"
echo "EOF"
echo "-----------------------------------------------------------"
echo ""
echo "3. TRANSFER FILES TO PRODUCTION using scp:"
echo "-----------------------------------------------------------"
echo "# Transfer the files (you will be prompted for password)"
echo "scp /tmp/deploy-package-${TIMESTAMP}.tar.gz root@${PROD_SERVER}:/tmp/"
echo "scp /tmp/puma.rb root@${PROD_SERVER}:/tmp/"
echo "-----------------------------------------------------------"
echo ""
echo "4. ON PRODUCTION SERVER, deploy the package:"
echo "-----------------------------------------------------------"
echo "# Extract the deployment package"
echo "cd /opt && rm -rf superapp-poc1_old && mv superapp-poc1 superapp-poc1_old 2>/dev/null || true"
echo "cd /opt && tar -xzf /tmp/deploy-package-${TIMESTAMP}.tar.gz"
echo ""
echo "# Copy the puma config"
echo "cp /tmp/puma.rb /opt/superapp-poc1/config/puma.rb"
echo ""
echo "# Set up directories and permissions"
echo "mkdir -p /opt/superapp-poc1/tmp/pids /opt/superapp-poc1/tmp/sockets /opt/superapp-poc1/log"
echo "chmod -R 755 /opt/superapp-poc1/tmp /opt/superapp-poc1/log"
echo ""
echo "# Start the server"
echo "cd /opt/superapp-poc1 && RAILS_ENV=production bundle exec puma -C config/puma.rb -d"
echo "-----------------------------------------------------------"
echo ""
echo "5. VERIFY the deployment:"
echo "-----------------------------------------------------------"
echo "# Check if Puma is running"
echo "ps aux | grep puma"
echo ""
echo "# Check the application"
echo "curl http://localhost:3000"
echo "-----------------------------------------------------------"
